# Generated by Django 5.1 on 2024-08-31 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fo_name', models.TextField(max_length=200)),
                ('fo_image', models.ImageField(blank=True, upload_to='images/')),
                ('fo_min', models.IntegerField()),
                ('fo_km', models.IntegerField()),
                ('fo_rating', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('rating', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('review', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='itemadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverytime', models.TextField()),
                ('deliveryaddress', models.TextField(max_length=200)),
                ('phonenumber', models.TextField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineorder.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineorder.menu')),
            ],
        ),
    ]
